name: Go CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Fetch Go-Swagger
      run: |
        download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
        jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url')
        curl -o /usr/local/bin/swagger -L'#' "$download_url"
        chmod +x /usr/local/bin/swagger
    - name: Yarn (frontend)
      run: (cd frontend && yarn)
    - name: Generate
      run: go generate -v ./...
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
