name: Release Go Binaries

on: 
  release:
    types: [created]
  workflow_dispatch:



jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          # windows/386 and darwin/386 seems useless 
          - goarch: "386"
            goos: windows 
          - goarch: "386"
            goos: darwin 
    steps:
    - uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.17
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./apiMain/"
        build_flags: -v
        binari_name: gobyoall-api
        extra_files: README.md api/generated-swagger.yml
        ldflags: -X "main.Version=${{ env.APP_VERSION }}" -X "main.BuildDateStr=${{ env.BUILD_TIME }}" -X "main.GitHash=${{ github.sha }}" -X 'main.IsDevStr=0'
    - uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.17
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_flags: -v
        binari_name: gobyoall
        ldflags: -X "main.Version=${{ env.APP_VERSION }}" -X "main.BuildDateStr=${{ env.BUILD_TIME }}" -X "main.GitHash=${{ github.sha }}" -X 'main.IsDevStr=0'
